# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
