# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_reading', '0002_let_age_and_grade_be_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_grade',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
