# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summer_reading', '0003_add_announcement_add_created_and_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
