# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_reading', '0004_add_author_and_title_to_anouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_school',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, choices=[('Alexander Hamilton Junior/Senior High School', 'Alexander Hamilton Junior/Senior High School'), ('Edgemont Junior/Senior High School', 'Edgemont Junior/Senior High School'), ('Maria Regina High School', 'Maria Regina High School'), ('R.J. Bailey School', 'R.J. Bailey School'), ('Scarsdale Middle School', 'Scarsdale Middle School'), ('Scarsdale High School', 'Scarsdale High School'), ('Solomon Schechter School', 'Solomon Schechter School'), ('Woodlands Middle/High School', 'Woodlands Middle/High School'), ('Other', 'Other')], default='Alexander Hamliton Junior/Senior High School', max_length=64),
        ),
    ]
