# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_reading', '0006_add_rules_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
